version: '3'

services:
  flask:
    build: ./flask
    platform: linux/arm64/v8
    ports:
      - "5000"
    expose:
      - 5000

  nginx:
    build: ./nginx
    depends_on:
      - flask
    ports:
      - "8080:80"
